services:
  db:
    image: pgvector/pgvector:pg16
    container_name: my_ai_search_db
    environment:
      POSTGRES_USER: dodanil
      POSTGRES_PASSWORD: dodanil
      POSTGRES_DB: my_ai_search
    ports:
      - "6432:5432"  # пробрасываем на хост, чтобы можно было подключаться снаружи (опционально)
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - my_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dodanil -d my_ai_search"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: my_ai_search_app

    ports:
      - "7777:8000"

    depends_on:
      db:
        condition: service_healthy

    env_file:
      - .env
    environment:
      HF_HOME: /cache/huggingface
    volumes:
      - ./src:/app/src
      - hf_cache:/cache/huggingface

    networks:
      - my_network
    command: fastapi dev src/main.py --host 0.0.0.0 --port 8000

volumes:
  pg_data:
  hf_cache:

networks:
  my_network:
    external: true  # если сеть уже создана, или уберите, если хотите, чтобы compose создал её сам