FROM python:3.14.0

WORKDIR /app

# Копируем зависимости сначала (для кеширования)
COPY requirements.txt requirements.txt
RUN --mount=type=cache,target=/root/.cache/pip python -m pip install -r requirements.txt

# Копируем весь проект
COPY . .

# Команда по умолчанию: миграции и запуск
CMD ["/bin/sh", "-c", "alembic upgrade head && python src/main.py"]